Resources:
      LaunchConfig:
        Type: 'AWS::AutoScaling::LaunchConfiguration'
        Properties:
          KeyName: new.learn-key.pe
          ImageID: ami-0d37e07bd4ff37148
          InstanceType: t2.micro
          SecurityGroups: AWS::EC2::InstanceSecurityGroup 
          LaunchConfigurationName: Task1LaunchConfiguration
          Userdata:
            Fn::Base64: !Sub |
              #!/bin/bash
              yum update -y
              yum install -y httpd.x86_64
              systemctl start httpd.service
              systemctl enable httpd.service
              echo "Hello World" > /var/www/html/index.html


Resources:
      AutoScalingGroup:
        Type: 'AWS::AutoScaling::AutoscalingGroup'
        Properties:
          AutoScalingGroupName:  Task1 Autoscaling Group
          Cooldown: 300
          DesiredCapacity: String
          LaunchConfigurationName: Task1LaunchConfiguration
          MaxSize: '2'
          MinSize: '2'
          VPCZoneIdentifier: 
            AWS::EC2::Subnet: Privatesubnet

Resource:
      ApplicationLoadBalancer:
        Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
        Properties:
          Subnets: 
            !Ref PublicSubnet1
            !Ref PublicSubnet
Resource:
      ALBListeners:
        Type: 'AWS::ElasticLoadBalancingV2::Listener'
        Properties:
          LoadBalancerArn: !Ref ApplicationLoadBalancer
          Port: 80
          Protocol: HTTP
          Default action:
            - Type: forward
              TargetGroupArn: !Ref ALBTargetgroup
Resource:
      ALBTargetGroup:
        Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
        Properties:
          HealthCheckIntervalSeconds: 30
          HealthCheckTimeoutSeconds: 5
          HealthyThresholdCount: 3
          Port: 80
          Protocol: HTTP
          UnhealthyThresholdCount: 5
          vpcid: !Ref VPCID

Resource:
      InstanceSecurityGroup: 
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
          GroupDescription: Enable SSH access and HTTP access on the inbound port
          SecurityGroupIngress:
            IpProtocol: tcp
            FromPort: '80'
            ToPort: '80'
            SourceSecurityGroupId: !Select 
            - 0
            - !GetAtt 
              - ApplicationLoadBalancer
              - SecurityGroups
            - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: !Ref SSHLocation
            VpcId:  !Ref VPC
Outputs:
  URL:
    Description: URL of the website
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - ApplicationLoadBalancer
          - DNSName
